using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;

namespace EditorTools.ConstantsGeneration
{
    public static class EnumGenerator
    {
        public static void GenerateEnum(string path, string enumName, List<string> elements)
        {
            var sb = new StringBuilder();
            
            sb.AppendLine("// AUTOGENERATED //");
            sb.AppendLine("");
            
            sb.AppendLine("namespace Constant");
            sb.AppendLine("{");

            sb.AppendLine($"    public enum {enumName}");
            sb.AppendLine("    {");
            
            foreach (var element in elements)
            {sb.AppendLine($"        {element},");}
            
            sb.AppendLine("    }");
            sb.AppendLine("}");
            
            File.WriteAllText(path, sb.ToString());
            
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
        }
    }
}