using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;

namespace EditorTools.ResourcesManagement
{
    public static class GlobalRGenerator
    {
        private const string PREFABS_ROOT_FOLDER = "Assets/_Main/Resources/Prefab";
        private const string GLOBAL_R_PATH = "Assets/_Main/Scripts/Global/R.cs";
        
        [MenuItem("Tools/Generate GlobalR")]
        public static void Generate()
        {
            var guids = AssetDatabase.FindAssets("t:Prefab", new[] { PREFABS_ROOT_FOLDER });
            
            var pathNamesMap = new Dictionary<string, string>();
            
            var paths = guids
                .Select(AssetDatabase.GUIDToAssetPath)
                .Select(path =>
                    {
                        var index = path.IndexOf("Resources/", StringComparison.Ordinal);
                        var relativePath = path[(index + "Resources/".Length)..];
                        return Path.ChangeExtension(relativePath, null);
                    })
                .ToArray();

            var names = paths.Select(Path.GetFileNameWithoutExtension).ToList();

            for (var i = 0; i < paths.Length; i++)
            { pathNamesMap.Add(paths[i], names[i]); }
            
            var sb = new StringBuilder();
            
            sb.AppendLine("// AUTOGENERATED //");
            sb.AppendLine("");
            
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("");
            
            sb.AppendLine("public static class R");
            sb.AppendLine("{");

            foreach (var (path, name) in pathNamesMap)
            { sb.AppendLine($"    public static GameObject {name}Prefab => Resources.Load<GameObject>(\"{path}\");"); }
            
            sb.AppendLine("}");
            
            File.WriteAllText(GLOBAL_R_PATH, sb.ToString());
            
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
        }
    }
}