// AUTOGENERATED //

using UnityEngine;

public static class R
{
    public static GameObject ChangeStageWindowPrefab => Resources.Load<GameObject>("Prefab/UI/2 Window/ChangeStageWindow");
    public static GameObject StageChoiceButtonPrefab => Resources.Load<GameObject>("Prefab/UI/Other/StageChoiceButton");
    public static GameObject UIPrefab => Resources.Load<GameObject>("Prefab/UI/UI");
}
